### ISSUE TITLE
Can't get attribute 'DetectionModel'

### ISSUE THREAD

**Issue by sipvoip** [cobryan05/Yolo2Mqtt#1]
yolo2mqtt    | ERROR:Worker_driveway:Failed to load model [/config/yolov5m.pt]: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/app/submodules/yolov5/models/yolo.py'>

I am able to run my model from yolov5 detect.py

P.S. I had to change depends_on: to mqtt from mqtt2 in the original.

**Comment by cobryan05** [comment]
> I am able to run my model from yolov5 detect.py

Are you able to run it in the yolov5 submodule of this repo, or are you running it elsewhere?

yolov5 does not seem shy about breaking binary compatibility with their models, so my first guess would be "they broke it."  A quick google for your error message comes up with this: https://github.com/ultralytics/yolov5/issues/9151   so it looks like they changed something a couple months ago.

If you are training you own model, make sure you are training it with the same yolov5 version that you are running in this repo. 

If you are not training your own model, I believe that yolov5 automatically downloads 'yolov5m.pt'  if it is missing.   The yolov5 submodule does this internally, it's not something I set up.  I bet it's downloading a 'new' version of the model. I think this repo is using yolov5 6.0, so you might try the models from https://github.com/ultralytics/yolov5/releases/tag/v6.0 .

**Comment by sipvoip** [comment]
I am training my own model, I when I try training on that I get:

RuntimeError: result type Float can't be cast to the desired output type long int

I will work on fixing that and try gain.

**Comment by sipvoip** [comment]
So ya, for whatever reason, I can build my model on new, but not old yolov5

**Comment by cobryan05** [comment]
Maybe if you just pull up the yolov5 submodule then yolo2mqtt will be able to read the new models?

`yolo2mqtt/submodules/yolov5> git fetch; git checkout remotes/origin/master`

**Comment by sipvoip** [comment]
Yep, tried that, and now I get:

ERROR:Worker_driveway:Failed to load model [/config/yolov5m.pt]: attempt_load() got an unexpected keyword argument 'map_location'

BTW, using NVIDIA

yolo:
  device: "cuda"

**Comment by cobryan05** [comment]
I think 'map_location' is now 'device'. Check  submodules/trackerTools/yoloInference.py  and change all instances of 'map_location' to 'device'.

After updating yolov5 you'll want to make sure to install their new dependencies. (If you use a virtualenv, be sure to have it active):

```
yolo2mqtt/submodules/yolov5> git fetch; git checkout remotes/origin/master
yolo2mqtt/submodules/yolov5> python -m pip install --upgrade -r requirements.txt
```

If you are building via docker and don't know how to otherwise get the requirements fixed, a quick hack might be to simply merge the contents of the new submodules/yolov5/requirements.txt  into the root requirements.txt before building the docker container. Might want to keep the root's torch==1.10.2 though , since that is what the docker container is built with. (Or if keeping that doesn't work, then update the dockerfile with a newer version? Or maybe it will just sort itself out while building the docker container :) )

Also, I haven't tested this on cuda (the fileserver I run this on does not have a GPU), so testing first on 'cpu' might not be a bad idea

**Comment by sipvoip** [comment]
Any interest in getting this to work with latest yolo5? Happy to pay you via Paypal, just let me know how much via email nathan at robotics.net

**Comment by cobryan05** [comment]
We've moved to a new house, so I need to re-train my network. My fileserver has also acquired an old GTX 970 over the past year, so I will be updating this to work with Docker/CUDA and am going to bump up to Yolo v7. Expect some updates in the next few weeks.

**Comment by sipvoip** [comment]
Cool, yolo v7 is cool, but why not just go to v8? I have been using it and it looks state-of-the-art.

**Comment by cobryan05** [comment]
I don't remember if I was even aware of a V8 or if there was a reason I chose v7.  The API change between the v5 and v7 was essentially zero, and since v8 appears to be back to ultralytics I expect the same there. I bet updating to v8 or even switching between them will be fairly simple, so I'd say expect v8 support (but I'm not committing to anything :-))

**Comment by cobryan05** [comment]
I think https://github.com/cobryan05/Yolo2Mqtt/commit/b567a9d181e3984c830871a47b65c164ce3ba4ca gets things going with Yolov7 (needs a submodule update for TrackerTools).  I'll probably take a look at YoloV8 at some point, but already had this mostly ready and Yolov7 conveniently is already in Pip.
I'll probably try out YoloV8 in the next few weeks. I'd be it is a super easy change to TrackerTools (here is the V7 change https://github.com/cobryan05/TrackerTools/commit/b9aa759f85538aeeb5f72737f88025f86be30a1f )  I just haven't looked yet.

**Comment by sipvoip** [comment]
Thank! I am not a programmer, but I cobbled together something that is
working for yolov8.

import paho.mqtt.client as mqttClient
import time
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('yolov8x.pt')

# Define path to video file
source = 'rtsp://10.88.64.102:7447/iTRNax6vQJlyyBFN'

# Broker callback
def on_connect(client, userdata, flags, rc):
    if rc == 0:
        print("Connected to broker")
        global Connected
        Connected = True
    else:
        print("Connection failed")

Connected = False


# Broker info
broker_address= "10.88.64.4"
port = 1883
client = mqttClient.Client("Marge")
client.on_connect=on_connect

# Connect to OpenHab MQTT
client.connect(broker_address, port=port)
client.loop_start()

time.sleep(1)

# Run inference on the source
results = model.predict(source, stream=True, imgsz=1280, verbose=False,
conf=0.85)  # generator of Results objects

for result in results:
    boxes = result.boxes.cpu().numpy()
    for box in boxes:
        conf = box.conf[0]
        cls = box.cls[0]
        if cls==0.0:
            carrier = "Amazon"
        elif cls==1.0:
            carrier = "Fedex"
        elif cls==2.0:
            carrier = "UPS"
        print(carrier, conf)
        client.publish("/driveway/delivery",carrier)

><>
nathan stratton

**Comment by cobryan05** [comment]
With https://github.com/cobryan05/Yolo2Mqtt/commit/d59084aee9b1115a61f0a3203c6929d34381709b  this should support yolov5, yolov7 and yolov8. The model's config now have a yoloVersion parameter. (Don't forget to run a 'git submodule update' to pull in the submodule changes)
