### ISSUE TITLE
aler9/rtsp-simple-server -> MediaMTX

### ISSUE THREAD

**Issue by apbodrov** [cobryan05/Yolo2Mqtt#2]
Hello. rtsp-simple-server was renamed and Dockerfile is broken right now

https://github.com/bluenviron/mediamtx/releases/tag/v0.19.3 works for example

**Comment by cobryan05** [comment]
Thanks for the report! I'm setting up Yolo2Mqtt at a new place, so I expect I will work through any issues like this in the next few weeks

**Comment by cobryan05** [comment]
Should be fixed by https://github.com/cobryan05/Yolo2Mqtt/commit/4058fbd0f8900163187687eb20cbf82f2cc77144
